# https://nixpacks.com/docs/configuration

[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
commands = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
