# https://nixpacks.com/docs/configuration
[node]
version = "22"

[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
commands = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
